version: '3'

services:
  text_generation_api:
    build: ./text_generation_api
    ports:
      - "5000:5000"
    volumes:
      - ./config:/text_generation_api/config
      - ./responses.db:/responses.db
    environment:
      - CHECKPOINT=MBZUAI/LaMini-Flan-T5-783M
      - PORT=5000
      - PREPROMPT=Below is an instruction that describes a task. Write a response that appropriately completes the request. \n\n### Instruction:\n{instruction}\n\n### Response:\n
    networks:
      - internal

  telegram_bot:
    build: ./telegram_bot
    depends_on:
      - text_generation_api
    volumes:
      - ./config:/app/config
      - ./telegram_bot:/app/telegram_bot
    environment:
      - TELEGRAM_BOT_TOKEN=token
      - PORT=5000
      - TEXT_GENERATION_HOST=text_generation_api
    networks:
      - internal

networks:
  internal:
